services:

  backend:
    volumes:
      - ./backend:/app
    # Usamos 'fastapi dev' para habilitar el Hot Reload automático
    command: fastapi dev app/main.py --host 0.0.0.0

  frontend:
    volumes:
      - ./frontend:/app
      # Evitamos que los node_modules locales sobrescriban los del contenedor
      - /app/node_modules
    # Usamos el servidor de desarrollo de Vite
    command: npm run dev -- --host
    labels:
      # Cambiamos el puerto para que Traefik apunte al servidor de Vite (5173) en lugar de Nginx (80)
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=5173
